version: '2'
services:
  web:
    image: node
    container_name: young-node
    working_dir: /usr/src/app
    expose:
      - "3000"
    entrypoint:
      - "npm"
      - "run"
      - "prod"
    restart: always
    networks:
     - nginx-proxy
    volumes:
      - "./:/usr/src/app"
    environment:
      - VIRTUAL_HOST=young.k-3soft.com
networks:
  nginx-proxy:
    external:
      name: serverservices_default